version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16  # Specify the Node.js runtime version
    commands:
      - echo "Installing dependencies..."
      - npm install

  pre_build:
    commands:
      - echo "Running pre-build commands..."
      # You can include any commands you need to run before the build phase here

  build:
    commands:
      - echo "Running build commands..."
      - npm test  # Run your test suite

  post_build:
    commands:
      - echo "Running post-build commands..."
      # Any commands after the build can go here, such as packaging or notifications

artifacts:
  files:
    - '**/*'
  discard-paths: no
